/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.apache.skywalking.apm.plugin.jdbc;

import java.lang.reflect.Method;
import java.sql.Connection;
import java.sql.PreparedStatement;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance;
import org.apache.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor;
import org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.MethodInterceptResult;
import org.apache.skywalking.apm.plugin.jdbc.trace.ConnectionInfo;

/**
 * {@link JDBCPrepareStatementInterceptor} return {@link SWPreparedStatement} instance that wrapper the real
 * PreparedStatement instance when the client call <code>prepareStatement</code> method.
 *
 * <pre>
 * (JDBCPrepareStatementInterceptor 返回 SWPreparedStatement 实例，该实例在客户端调用 prepareStatement() 时 包装了真实的 PreparedStatement 实例。)
 *
 * 增强类：java.sql.Connection 的实现类
 * 增强方法：
 *          PreparedStatement prepareStatement(String sql)
 *          PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
 *          PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
 *          PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
 *          PreparedStatement prepareStatement(String sql, int columnIndexes[])
 *          PreparedStatement prepareStatement(String sql, String columnNames[])
 * </pre>
 */
public class JDBCPrepareStatementInterceptor implements InstanceMethodsAroundInterceptor {
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        MethodInterceptResult result) throws Throwable {

    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes,
        Object ret) throws Throwable {
        // 如果 java.sql.Connection 的实现类 的 增强域（ConnectionInfo） 为空，则不扩展 ret（PreparedStatement）
        if (objInst.getSkyWalkingDynamicField() == null) {
            return ret;
        }
        // 将 ret（PreparedStatement）替换为 SWPreparedStatement 对象
        return new SWPreparedStatement((Connection) objInst, (PreparedStatement) ret, (ConnectionInfo) objInst.getSkyWalkingDynamicField(), (String) allArguments[0]);
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments,
        Class<?>[] argumentsTypes, Throwable t) {

    }
}
